<?php

return [

    'lead_contacted'                   => 'E-mail enviado para :value1 via :value2',
    'activity_create_comment'          => 'Novo comentário postado em  :value1',
    'activity_update_invoice'          => 'Fatura :value1 para o cliente :value2 foi atualizada',
    'activity_create_invoice'          => 'Fatura :value1 criada para o cliente :value2',
    'activity_update_project'          => 'Projeto :value1 para o cliente :value2 foi atualizada',
    'activity_create_deal'             => 'Oferta :value1 para cliente :value2 foi criada',
    'activity_update_deal'             => 'Oferta :value1 para cliente :value2 foi atualizada',
    'activity_create_lead'             => 'Lead :value1 de :value2 foi criado',
    'activity_update_lead'             => 'Lead :value1 foi atualizado',
    'activity_create_estimate'         => 'Orçamento :value1 para o cliente :value2 foi criado',
    'activity_update_estimate'         => 'Orçamento :value1 para o cliente :value2 foi atualizado',
    'activity_create_creditnote'       => 'Nota de crédito :value1 foi criada para o cliente :value2',
    'activity_update_creditnote'       => 'Nota de crédito :value1 para o cliente :value2 foi atualizada',
    'activity_create_project'          => 'Projeto :value1 para o cliente :value2 foi criado',
    'activity_create_task'             => 'Tarefa :value1 foi criado para o projeto :value2',
    'activity_update_task'             => 'Tarefa :value1 para o projeto :value2 foi atualizada',
    'activity_update_issue'            => 'O bug :value1 para o projeto :value2 foi atualizado',
    'activity_create_issue'            => 'Um bug :value1 foi relatado para o projeto :value2',
    'activity_update_timer'            => 'Entrada de hora (:value1) foi atualizada in projeto :value2',
    'activity_create_timer'            => 'Uma nova entrada de hora (:value1) foi adicionado ao projeto :value2',
    'activity_delete_timer'            => 'Entrada de hora (:value1) foi eliminado no projeto :value2',
    'activity_create_milestone'        => 'Milestone :value1 foi criado para o projeto :value2',
    'activity_create_ticket'           => 'Ticket :value1 para departamento :value2 foi criado',
    'activity_update_ticket'           => 'Ticket :value1 para departamento :value2 foi atualizado',
    'activity_create_contract'         => 'um novo contrato :value1 foi criado para o cliente :value2',
    'activity_update_contract'         => 'O contrato :value1 para o cliente :value2 foi atualizado',
    'activity_sent_contract'           => 'O contrato :value1 foi enviado para :value2',
    'activity_update_article'          => 'O artigo :value1 na categoria :value2 foi atualizado',
    'activity_create_article'          => 'O artigo :value1 foi criado na categoria :value2',
    'activity_update_expense'          => 'Despesa :value1 para o cliente :value2 foi atualizada',
    'activity_create_expense'          => 'Despesa :value1 para o cliente :value2 foi criada',
    'activity_payment_of'              => 'O pagamento de :value1 foi recebido de :value2',
    'activity_team_removed'            => 'Membro da equipe :value1 foi removido do projeto :value2',
    'activity_update_milestone'        => 'O marco :value1 no projeto :value2 foi atualizado',
    'activity_convert_lead'            => 'Lead :value1 convertido em oferta',
    'activity_closed_ticket'           => 'Ticket :value1 foi fechado em :value2',
    'activity_convert_estimate'        => 'O orçamento :value1 no valor de :value2 foi convertido em fatura',
    'activity_accepted_estimate'       => 'O orçamento :value1 no valor de :value2 foi aceito',
    'activity_declined_estimate'       => 'O orçamento :value1 no valor de :value2 foi recusado',
    'activity_sent_creditnote'         => 'Nota de crédito no valor de :value1 para o cliente :value2 foi enviada.',
    'activity_sent_invoice'            => 'Fatura no valor de :value1 foi enviada para :value2',
    'activity_sent_estimate'           => 'Orçamento no valor de :value1 foi enviado para :value2',
    'activity_rejected_contract'       => 'O contrato :value1 para o cliente :value2 foi recusado',
    'activity_viewed_contract'         => 'o contrato :value1 foi visto',
    'activity_close_project'           => 'O projeto :value1 para o cliente :value2 foi fechado',
    'activity_delete_user'             => 'O usuário :value1 foi deletado',
    'activity_update_payment'          => 'O pagamento :value2 no valor de :value1 foi atualizado',
    'activity_delete_invoice'          => 'A fatura :value1 para o cliente :value2 foi deletada',
    'activity_viewed_invoice'          => 'A fatura :value1 foi visualizada pelo cliente',
    'activity_viewed_estimate'         => 'Orçamento :value1 foi visto pelo cliente',
    'activity_update_setting'          => 'Definições de configuração de aplicativo modificadas',
    'activity_delete_issue'            => 'O bug :value1 foi deletado no projeto :value2',
    'activity_invoice_polite_reminder' => 'Lembrete para fatura :value1 enviado para :value2',
    'activity_invoice_firm_reminder'   => 'Segundo lembrete para fatura :value1 para :value2',
    'activity_invoice_final_reminder'  => 'Lembrete final da fatura :value1 para :value2',
    'activity_delete_ticket'           => 'O Ticket :value1 foi excluído',
    'activity_create_todo'             => 'Todo :value1 created',
    'activity_delete_project'          => 'Project :value1 with cost :value2 was deleted',
    'activity_delete_expense'          => 'Expense :value1 with cost :value2 was deleted',
    'activity_delete_deal'             => 'Deal :value1 for client :value2 was deleted',
    'activity_delete_lead'             => 'Lead :value1 from source :value2 was deleted',

];
