<?php
return [
    'action_not_allowed'             => 'Ação NÃO permitida (Permissão negada)',
    'your_system_is_up_to_date'      => 'O seu sistema está atualizado',
    'update_found'                   => 'Atualização Encontrada',
    'current_version'                => 'Versão Atual',
    'downloading_update'             => 'Baixando a atualização....',
    'error_during_download'          => 'Erro durante o download.',
    'ok'                             => 'OK',
    'maintenance_mode_activated'     => 'Modo de manutenção Ativado',
    'maintenance_mode_deactivated'   => 'Modo de manutenção desativado',
    'database_migrated'              => 'Migração de banco de dados bem-sucedida',
    'system_updated_to_version'      => 'Sistema atualizado para versão',
    'error_during_update'            => 'Erro durante a atualização (!!verifique o arquivo de atualização!!) --TRY para restaurar o status do OLD ........... ',
    'changelog'                      => 'Changelog',
    'directory'                      => 'Diretório',
    'file'                           => 'Arquivo',
    'commands_successfully_executed' => 'Comandos executados com sucesso.',
    'error_during_command_execution' => 'Erro durante a execução dos comandos.',
    'could_not_save_update'          => 'Não foi possível salvar nova atualização (Verifique se /storage/app/tmp/ tem permissão de escrita). Atualização abortada.',
    'failed'                         => 'Falhou',
    'backup_folder_located_in'       => 'Pasta de backup está localizada em:',
    'restore_system_command'         => 'Desativar o modo de manutenção manualmente usando',
    'restored'                       => 'Restaurado',
    'Update_Now'                     => 'Atualizar agora',
    'Update_Available'               => 'Atualização disponível',
    'Updated'                        => 'Atualizado',
    'Updating'                       => 'Atualizando',
    'error_try_again'                => 'Erro.Tente novamente',
];
