<?php
return [
    'action_not_allowed'             => 'İzin Verilmeyen Yöntem',
    'your_system_is_up_to_date'      => 'Sisteminiz zaten son sürüme yükseltilmiş',
    'update_found'                   => 'GÜNCELLEME BULUNDU',
    'current_version'                => 'aktif versiyon',
    'downloading_update'             => 'Güncelleniyor, dosyalar indiriliyor ...',
    'error_during_download'          => 'İndirme sırasında hata oluştu',
    'ok'                             => 'TAMAM',
    'maintenance_mode_activated'     => 'Sistem Bakım Modu',
    'maintenance_mode_deactivated'   => 'Maintenance mode deactivated',
    'database_migrated'              => 'Database migrations successful',
    'system_updated_to_version'      => 'Sistem Güncel versiyona yükseltildi',
    'error_during_update'            => 'GÜNCELLEME YAPILIRKEN HATA  OLUŞTU (!! güncelleme arşivini kontrol edin !!) - ESKİ durumuna geri yükleniyor ...',
    'changelog'                      => 'Değişim Günlüğü',
    'directory'                      => 'Dizin',
    'file'                           => 'Dosya',
    'commands_successfully_executed' => 'Komutlar başarıyla yürütüldü',
    'error_during_command_execution' => ' Komutlar yürütme sırasında hata oluştu',
    'could_not_save_update'          => 'Yeni güncelleme indirilemedi(tmp/ yazma iznini ve yeterli disk alanı olup olmadığını kontrol edin). Güncelleme iptal edildi',
    'failed'                         => 'BAŞARISIZ',
    'backup_folder_located_in'       => 'BYedekleme klasörü:',
    'restore_system_command'         => 'DShell komutu ile Sistemi Durumunu geri yüklemeyi unutmayın.Sistem Yöneticisine başvurunuz. komut:',
    'restored'                       => 'GERİ YÜKLENDİ',
    'Update_Now'                     => 'Hemen Güncelle',
    'Update_Available'               => 'Güncelleme Mevcut',
    'Updated'                        => 'Güncellendi',
    'Updating'                       => 'Güncelleniyor',
    'error_try_again'                => 'Hata oluştu.Tekrar deneyiniz',
];
