<?php

return [
    'cal_su'        => 'Ne',
    'cal_mo'        => 'Po',
    'cal_tu'        => 'Ut',
    'cal_we'        => 'Sr',
    'cal_th'        => 'Če',
    'cal_fr'        => 'Pe',
    'cal_sa'        => 'Su',
    'cal_sun'       => 'Sub',
    'cal_mon'       => 'Pon',
    'cal_tue'       => 'Uto',
    'cal_wed'       => 'Sre',
    'cal_thu'       => 'Čet',
    'cal_fri'       => 'Pet',
    'cal_sat'       => 'Sub',
    'cal_sunday'    => 'Nedelja',
    'cal_monday'    => 'Ponedeljak',
    'cal_tuesday'   => 'Utorak',
    'cal_wednesday' => 'Sreda',
    'cal_thursday'  => 'Četvrtak',
    'cal_friday'    => 'Petak',
    'cal_saturday'  => 'Subota',
    'cal_jan'       => 'Jan',
    'cal_feb'       => 'Feb',
    'cal_mar'       => 'Mar',
    'cal_apr'       => 'Apr',
    'cal_may'       => 'Maj',
    'cal_jun'       => 'Jun',
    'cal_jul'       => 'Jul',
    'cal_aug'       => 'Avg',
    'cal_sep'       => 'Sep',
    'cal_oct'       => 'Okt',
    'cal_nov'       => 'Nov',
    'cal_dec'       => 'Dec',
    'cal_january'   => 'Januar',
    'cal_february'  => 'Februar',
    'cal_march'     => 'Mart',
    'cal_april'     => 'April',
    'cal_mayl'      => 'Maj',
    'cal_june'      => 'Jun',
    'cal_july'      => 'Jul',
    'cal_august'    => 'Avgust',
    'cal_september' => 'Septembar',
    'cal_october'   => 'Oktobar',
    'cal_november'  => 'Novembar',
    'cal_december'  => 'Decembar',

];
